; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = Simulator
boards_dir = board

[env]

[env:Servo]
platform = ststm32
framework = arduino
board = genericSTM32G431CB
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
build_src_filter = +<STM32/**>
test_filter = test_servo
test_ignore = 
	test_simulator
	test_inputBridge
	test_unit
build_unflags = 
build_flags = 
	-Wl,-Map,.pio/build/Servo/firmware.map

[env:InputBridge]
platform = ststm32
framework = arduino
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
board = genericSTM32G030C8T6
build_src_filter = +<InputBridge/**>
test_filter =
test_ignore = 
	test_simulator
	test_servo
	test_unit

[env:Simulator]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<Simulator/**>
test_filter = test_simulator
test_ignore = 
	test_servo
	test_inputBridge
	test_unit
lib_deps =
	ArduinoFake
build_flags = 
	-std=gnu++17
	-DDISABLE_DEBUG
	-Wno-missing-template-arg-list-after-template-kw

[env:Unit]
platform = native
test_framework = unity
test_filter = test_unit
test_ignore = 
	test_servo
	test_simulator
	test_inputBridge
lib_deps =
	ArduinoFake
build_flags = 
	-std=gnu++17
	-DDISABLE_DEBUG
	-Wno-missing-template-arg-list-after-template-kw
