; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
upload_protocol = stlink
debug_tool = stlink

[env:STM32G431CB]
platform = ststm32
board = genericSTM32G431CB
build_flags =
 -Wl,-Map,.pio/build/STM32G431CB/firmware.map

[env:GD32F130G8]
platform = gd32
board = genericGD32F130G8
build_flags =
;  -Wl,--defsym=__stack_size=0x400
 -Wl,-Map,.pio/build/GD32F130G8/firmware.map